### PR TITLE
Add react-native-maps-directions

### PR DESCRIPTION
**Pull request by bramus**

### CODE REVIEW

**Comment by jimmylee** [comment]
Super cool! Thanks for submitting this!

**Comment by bramus** [comment]
Thanks @jimmylee! Any idea when a new deploy will be triggered? When checking https://www.native.directory/updated/google-maps for example (or when searching for the package by name) I don't see it listed.

**Comment by jimmylee** [comment]
@bramus super sorry about that! Will deploy something soon, trying to figure out what to do with this error where github is rate limiting my work ip address.

**Comment by jimmylee** [comment]
Here you are: `http://native.directory/?search=react-native-maps` - so sorry about that.

**Comment by bramus** [comment]
No worries there @jimmylee. I see that it's been deployed now, thanks for that :)

**Pull request merged**
