### PR TITLE
Add AutoCompleteTextView - android only

### PR DESCRIPTION
**Pull request by Noitidart**

### CODE REVIEW

**Comment by jimmylee** [comment]
Have you used this library before? Looks like it has low engagement

**Comment by Noitidart** [comment]
Thanks @jimmylee  for looking into it. I'm struggling to install it automatically. I tried to help the author but I'm not a native dev. It's a very important component used in many Android apps. I'm trying to get this name out there to attract some PRs some motivation/help to the main author.

The engagement on this autocomplete module is about same engagement on my polished module here - https://github.com/Noitidart/react-native-buttonex - it would be awesome if you could allow this in. This auto complete module is much better off then those outdated modules that are still in the list.

**Comment by Noitidart** [comment]
@jimmylee we are putting in major work on this. It's almost polished up and ready to go. We just need 24 more hours please. :) It would be aweomse if you could premptively merge. You can see our progress in the issues and pr sections:

https://github.com/rajsuvariya/autocompletetextview/issues

https://github.com/rajsuvariya/autocompletetextview/pulls

**Comment by Noitidart** [comment]
Author is on vacation till 15th and will merge from dev to master then

**Comment by jimmylee** [comment]
Okay @Noitidart thanks for the updates.

**Comment by Noitidart** [comment]
He hasn't merged from dev to master yet. Will update you as soon as he does. :)

**Comment by jimmylee** [comment]
@Noitidart I'll close this for now, feel free to re-open when you have an update for us :)

**Pull request closed without merging**
