### PR TITLE
Add Falling & Scaling Drawer 🎨

### PR DESCRIPTION
**Pull request by deadcoder0904**

### CODE REVIEW

**Comment by jimmylee** [comment]
Formatting looks all messed up, can you fix it? Thanks :)

**Comment by deadcoder0904** [comment]
Looks alright to me

**Comment by jimmylee** [comment]
@deadcoder0904 here are a couple of things you should pay attention to:

1.

screen shot 2017-11-01 at 11 11 15 am

- We will not merge commits that break existing formatting. Are you able to tell that your indentation is a little off here?

2.

screen shot 2017-11-01 at 11 13 19 am

- Github is warning me about illegal JSON characters. You're missing a opening `{`.

Let me know if you have any other questions 😎

**Comment by deadcoder0904** [comment]
Whoops that was some merging issue I did on Github. It was while resolving confilcts things messed up. Also, my prettier 😂

**Comment by jimmylee** [comment]
Again, your indentation is incorrect, you may have a setting where you have custom tab length in your IDE.

**Comment by deadcoder0904** [comment]
Huh, I opened it in Atom which has no prettier & it shows its indented properly

**Comment by jimmylee** [comment]
What do you see when you click this? https://github.com/react-community/native-directory/pull/73/files

**Comment by deadcoder0904** [comment]
Hey @jimmylee thanks. But a suggestion, u can add a prettier formatter so that formatting won't be an issue. I think u need [Prettier Config File](https://github.com/prettier/prettier#configuration-file). It will be a little work but in the long run I think this might be useful. Now merge that one if its correct.

**Comment by deadcoder0904** [comment]
Ohh I messed up pretty badly again 😢 
I'll close this one & send another one 😹

**Pull request closed without merging**
